# Generated by Django 5.0.6 on 2025-02-06 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('converter', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='uploadedfile',
            name='output_file_type',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
