# Generated by Django 5.1.6 on 2025-02-13 00:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('converter', '0002_uploadedfile_output_file_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='uploadedfile',
            name='converted_file',
        ),
        migrations.RemoveField(
            model_name='uploadedfile',
            name='file_size',
        ),
        migrations.RemoveField(
            model_name='uploadedfile',
            name='file_type',
        ),
        migrations.RemoveField(
            model_name='uploadedfile',
            name='height',
        ),
        migrations.RemoveField(
            model_name='uploadedfile',
            name='output_file_name',
        ),
        migrations.RemoveField(
            model_name='uploadedfile',
            name='output_file_type',
        ),
        migrations.RemoveField(
            model_name='uploadedfile',
            name='width',
        ),
    ]
